// This file is auto-generated by @hey-api/openapi-ts

export const AuthorPublicSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        avatar: {
            type: 'string',
            title: 'Avatar',
            default: ''
        },
        bio: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bio'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'AuthorPublic',
    description: `作者信息（按 MVP 字段契约返回）。

约束/说明：
- 前端 \`PostCard\` 直接使用 \`author.avatar\` 作为图片 URL，因此后端必须返回该字段。
- 当前 \`User\` 模型没有头像与 bio 字段：本 MVP 先返回空字符串/None，由前端用 dicebear 兜底。
- \`id\` 为作者 public_id，用于跳转 TA 的资料页；已删除用户为 null。`
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const FollowStatusSchema = {
    properties: {
        following: {
            type: 'boolean',
            title: 'Following'
        }
    },
    type: 'object',
    required: ['following'],
    title: 'FollowStatus'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PostCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        body: {
            type: 'string',
            title: 'Body'
        },
        tag_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Tag Ids'
        }
    },
    type: 'object',
    required: ['title', 'body'],
    title: 'PostCreate'
} as const;

export const PostPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        timestamp: {
            type: 'string',
            title: 'Timestamp'
        },
        comments: {
            type: 'integer',
            title: 'Comments'
        },
        author: {
            '$ref': '#/components/schemas/AuthorPublic'
        },
        tags: {
            items: {
                '$ref': '#/components/schemas/TagPublic'
            },
            type: 'array',
            title: 'Tags'
        }
    },
    type: 'object',
    required: ['id', 'title', 'content', 'timestamp', 'comments', 'author'],
    title: 'PostPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ReplyCreateSchema = {
    properties: {
        body: {
            type: 'string',
            title: 'Body'
        }
    },
    type: 'object',
    required: ['body'],
    title: 'ReplyCreate'
} as const;

export const ReplyPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        timestamp: {
            type: 'string',
            title: 'Timestamp'
        },
        author: {
            '$ref': '#/components/schemas/AuthorPublic'
        },
        post_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Post Id'
        }
    },
    type: 'object',
    required: ['id', 'content', 'timestamp', 'author'],
    title: 'ReplyPublic'
} as const;

export const ResponseMessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'ResponseMessage'
} as const;

export const TagCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 50,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'TagCreate'
} as const;

export const TagPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_official: {
            type: 'boolean',
            title: 'Is Official',
            default: false
        },
        owner_public_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Public Id'
        }
    },
    type: 'object',
    required: ['id', 'name', 'slug'],
    title: 'TagPublic'
} as const;

export const TagsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TagPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'TagsPublic'
} as const;

export const TagsSuggestSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TagPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'TagsSuggest'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        username: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 150
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        phone_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone Number'
        },
        display_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 150
                },
                {
                    type: 'null'
                }
            ],
            title: 'Display Name'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        bio: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 160
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bio'
        },
        profile_metadata: {
            additionalProperties: true,
            type: 'object',
            title: 'Profile Metadata'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserProfileOutSchema = {
    properties: {
        user: {
            '$ref': '#/components/schemas/UserPublicPreview'
        },
        followers_count: {
            type: 'integer',
            title: 'Followers Count'
        },
        following_count: {
            type: 'integer',
            title: 'Following Count'
        },
        is_following: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Following'
        }
    },
    type: 'object',
    required: ['user', 'followers_count', 'following_count', 'is_following'],
    title: 'UserProfileOut'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        username: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 150
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        phone_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone Number'
        },
        display_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 150
                },
                {
                    type: 'null'
                }
            ],
            title: 'Display Name'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        bio: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 160
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bio'
        },
        profile_metadata: {
            additionalProperties: true,
            type: 'object',
            title: 'Profile Metadata'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        date_joined: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Joined'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserPublicPreviewSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        display_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Display Name'
        },
        username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        bio: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bio'
        },
        date_joined: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Joined'
        }
    },
    type: 'object',
    required: ['id', 'full_name', 'display_name', 'username', 'avatar_url', 'bio', 'date_joined'],
    title: 'UserPublicPreview',
    description: '对外展示的用户资料（不含邮箱等敏感字段）。'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        username: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 150
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        phone_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone Number'
        },
        display_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 150
                },
                {
                    type: 'null'
                }
            ],
            title: 'Display Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        username: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 150
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        phone_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone Number'
        },
        display_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 150
                },
                {
                    type: 'null'
                }
            ],
            title: 'Display Name'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        bio: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 160
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bio'
        },
        profile_metadata: {
            additionalProperties: true,
            type: 'object',
            title: 'Profile Metadata'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        username: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 150
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        phone_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone Number'
        },
        display_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 150
                },
                {
                    type: 'null'
                }
            ],
            title: 'Display Name'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        bio: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 160
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bio'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;