// This file is auto-generated by @hey-api/openapi-ts

export type AcceptInviteRequest = {
    invite_code: string;
};

export type AcceptInviteResponse = {
    message: string;
    space_id: string;
    role: string;
};

/**
 * 完成上传：携带与预签名相同的 JWT，用于二次校验与防篡改。
 */
export type AssetCompleteRequest = {
    upload_token: string;
    type?: (string | null);
};

export type AssetMeta = {
    logical_name: string;
    version: number;
    storage_key: string;
    size: number;
};

/**
 * 预签名请求：与文档约定一致。
 */
export type AssetPresignRequest = {
    logical_name: string;
    mime_type: string;
    size: number;
};

/**
 * 预签名响应：前端用 upload_url 发起 PUT，再调用 complete。
 */
export type AssetPresignResponse = {
    upload_url: string;
    upload_method?: string;
    upload_token: string;
    asset_meta: AssetMeta;
};

/**
 * 列表/详情返回给前端的资源结构。
 */
export type AssetPublic = {
    id: number;
    logical_name: string;
    version: number;
    type: string;
    size: number;
    storage_key: string;
    uploader_id: string;
    created_at?: (string | null);
};

export type AssetsPublic = {
    data: Array<AssetPublic>;
    count: number;
};

/**
 * 作者信息（按 MVP 字段契约返回）。
 *
 * 约束/说明：
 * - 前端 `PostCard` 直接使用 `author.avatar` 作为图片 URL，因此后端必须返回该字段。
 * - 当前 `User` 模型没有头像与 bio 字段：本 MVP 先返回空字符串/None，由前端用 dicebear 兜底。
 * - `id` 为作者 public_id，用于跳转 TA 的资料页；已删除用户为 null。
 */
export type AuthorPublic = {
    id?: (string | null);
    name: string;
    avatar?: string;
    bio?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type FollowStatus = {
    following: boolean;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PostCreate = {
    title: string;
    body: string;
    tag_ids?: Array<(string)>;
};

export type PostPublic = {
    id: string;
    title: string;
    content: string;
    timestamp: string;
    comments: number;
    author: AuthorPublic;
    tags?: Array<TagPublic>;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ReplyCreate = {
    body: string;
};

export type ReplyPublic = {
    id: string;
    content: string;
    timestamp: string;
    author: AuthorPublic;
    post_id?: (string | null);
};

export type ResponseMessage = {
    message: string;
};

export type SpaceCreate = {
    name: string;
    description?: (string | null);
    storage_quota?: (number | null);
};

export type SpaceInviteCreate = {
    role?: string;
    email?: (string | null);
    expires_in_days?: number;
};

export type SpaceInvitePublic = {
    invite_code: string;
    role: string;
    status: string;
    expires_at?: (string | null);
};

export type SpaceMemberPublic = {
    user_id: string;
    email: string;
    full_name?: (string | null);
    role: string;
    joined_at?: (string | null);
};

export type SpaceMemberRoleUpdate = {
    role: string;
};

export type SpaceMembersPublic = {
    data: Array<SpaceMemberPublic>;
    count: number;
};

export type SpacePublic = {
    id: string;
    name: string;
    description?: (string | null);
    owner_id: string;
    storage_quota: number;
    used_storage: number;
    current_user_role: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type SpacesPublic = {
    data: Array<SpacePublic>;
    count: number;
};

export type TagCreate = {
    name: string;
    description?: (string | null);
};

export type TagPublic = {
    id: string;
    name: string;
    slug: string;
    category?: (string | null);
    description?: (string | null);
    is_official?: boolean;
    owner_public_id?: (string | null);
};

export type TagsPublic = {
    data: Array<TagPublic>;
    count: number;
    next_cursor?: (string | null);
    has_more?: boolean;
};

export type TagsSuggest = {
    data: Array<TagPublic>;
    count: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    username?: (string | null);
    phone_number?: (string | null);
    display_name?: (string | null);
    avatar_url?: (string | null);
    bio?: (string | null);
    profile_metadata?: {
        [key: string]: unknown;
    };
    password: string;
};

export type UserProfileOut = {
    user: UserPublicPreview;
    followers_count: number;
    following_count: number;
    is_following: (boolean | null);
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    username?: (string | null);
    phone_number?: (string | null);
    display_name?: (string | null);
    avatar_url?: (string | null);
    bio?: (string | null);
    profile_metadata?: {
        [key: string]: unknown;
    };
    id: string;
    date_joined?: (string | null);
};

/**
 * 对外展示的用户资料（不含邮箱等敏感字段）。
 */
export type UserPublicPreview = {
    id: string;
    full_name: (string | null);
    display_name: (string | null);
    username: (string | null);
    avatar_url: (string | null);
    bio: (string | null);
    date_joined: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
    username?: (string | null);
    phone_number?: (string | null);
    display_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    username?: (string | null);
    phone_number?: (string | null);
    display_name?: (string | null);
    avatar_url?: (string | null);
    bio?: (string | null);
    profile_metadata?: {
        [key: string]: unknown;
    };
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    username?: (string | null);
    phone_number?: (string | null);
    display_name?: (string | null);
    avatar_url?: (string | null);
    bio?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type WikiCategoryCreateBody = {
    title: string;
    slug: string;
    parent_id?: (number | null);
};

export type WikiCategoryPublic = {
    id: number;
    parent_id: (number | null);
    slug: string;
    title: string;
    sort_order: number;
};

export type WikiDocCreateBody = {
    title: string;
    slug: string;
    markdown: string;
    category_id?: (number | null);
};

export type WikiDocumentDetailResponse = {
    slug: string;
    title: string;
    markdown: string;
    content_version: number;
    updated_at: (string | null);
};

export type WikiDocumentPublic = {
    id: number;
    category_id: (number | null);
    slug: string;
    title: string;
    content_version: number;
    updated_at: (string | null);
};

export type WikiSearchHit = {
    slug: string;
    title: string;
    excerpt: (string | null);
};

export type WikiSearchResponse = {
    hits: Array<WikiSearchHit>;
};

/**
 * 前端可自行组树：扁平列表 + parent 关系。
 */
export type WikiTreeResponse = {
    categories: Array<WikiCategoryPublic>;
    documents: Array<WikiDocumentPublic>;
};

export type KnowledgeGetKnowledgeTreeData = {
    spaceId: string;
};

export type KnowledgeGetKnowledgeTreeResponse = (WikiTreeResponse);

export type KnowledgeGetKnowledgeDocumentData = {
    slug: string;
    spaceId: string;
};

export type KnowledgeGetKnowledgeDocumentResponse = (WikiDocumentDetailResponse);

export type KnowledgeSearchKnowledgeData = {
    q: string;
    spaceId: string;
};

export type KnowledgeSearchKnowledgeResponse = (WikiSearchResponse);

export type KnowledgeCreateKnowledgeDocumentData = {
    requestBody: WikiDocCreateBody;
    spaceId: string;
};

export type KnowledgeCreateKnowledgeDocumentResponse = (WikiDocumentPublic);

export type KnowledgeCreateKnowledgeCategoryData = {
    requestBody: WikiCategoryCreateBody;
    spaceId: string;
};

export type KnowledgeCreateKnowledgeCategoryResponse = (WikiCategoryPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (ResponseMessage);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (ResponseMessage);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PostsCreatePostData = {
    requestBody: PostCreate;
};

export type PostsCreatePostResponse = (PostPublic);

export type PostsListPostsData = {
    limit?: number;
    skip?: number;
    tagId?: (string | null);
    tagSlug?: (string | null);
};

export type PostsListPostsResponse = (Array<PostPublic>);

export type PostsGetPostDetailData = {
    postId: string;
};

export type PostsGetPostDetailResponse = (PostPublic);

export type PostsListRepliesData = {
    postId: string;
};

export type PostsListRepliesResponse = (Array<ReplyPublic>);

export type PostsCreateReplyData = {
    postId: string;
    requestBody: ReplyCreate;
};

export type PostsCreateReplyResponse = (ReplyPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SpacesListSpacesResponse = (SpacesPublic);

export type SpacesCreateSpaceData = {
    requestBody: SpaceCreate;
};

export type SpacesCreateSpaceResponse = (SpacePublic);

export type SpacesGetSpaceDetailData = {
    spaceId: string;
};

export type SpacesGetSpaceDetailResponse = (SpacePublic);

export type SpacesListSpaceMembersData = {
    spaceId: string;
};

export type SpacesListSpaceMembersResponse = (SpaceMembersPublic);

export type SpacesCreateSpaceInviteData = {
    requestBody: SpaceInviteCreate;
    spaceId: string;
};

export type SpacesCreateSpaceInviteResponse = (SpaceInvitePublic);

export type SpacesCreateSpaceInviteLinkData = {
    requestBody: SpaceInviteCreate;
    spaceId: string;
};

export type SpacesCreateSpaceInviteLinkResponse = (SpaceInvitePublic);

export type SpacesResetSpaceInvitesData = {
    spaceId: string;
};

export type SpacesResetSpaceInvitesResponse = (ResponseMessage);

export type SpacesUpdateSpaceMemberRoleData = {
    memberUserId: string;
    requestBody: SpaceMemberRoleUpdate;
    spaceId: string;
};

export type SpacesUpdateSpaceMemberRoleResponse = (ResponseMessage);

export type SpacesRemoveSpaceMemberData = {
    memberUserId: string;
    spaceId: string;
};

export type SpacesRemoveSpaceMemberResponse = (ResponseMessage);

export type SpacesUploadStagedAssetData = {
    token: string;
};

export type SpacesUploadStagedAssetResponse = (unknown);

export type SpacesPresignSpaceAssetUploadData = {
    requestBody: AssetPresignRequest;
    spaceId: string;
};

export type SpacesPresignSpaceAssetUploadResponse = (AssetPresignResponse);

export type SpacesCompleteSpaceAssetUploadData = {
    requestBody: AssetCompleteRequest;
    spaceId: string;
};

export type SpacesCompleteSpaceAssetUploadResponse = (AssetPublic);

export type SpacesListSpaceAssetsData = {
    allVersions?: boolean;
    spaceId: string;
};

export type SpacesListSpaceAssetsResponse = (AssetsPublic);

export type SpacesDownloadSpaceAssetData = {
    assetId: number;
    spaceId: string;
};

export type SpacesDownloadSpaceAssetResponse = (unknown);

export type SpacesDeleteSpaceAssetData = {
    assetId: number;
    spaceId: string;
};

export type SpacesDeleteSpaceAssetResponse = ({
    [key: string]: (string);
});

export type SpacesAcceptSpaceInviteData = {
    requestBody: AcceptInviteRequest;
};

export type SpacesAcceptSpaceInviteResponse = (AcceptInviteResponse);

export type TagsListTagsNavResponse = (TagsPublic);

export type TagsListTagsData = {
    /**
     * 游标：仅返回 slug 大于该值的标签（按 slug 升序，字典序）
     */
    afterSlug?: (string | null);
    /**
     * 分页条数；不传则返回全量（发帖多选等场景）
     */
    limit?: (number | null);
};

export type TagsListTagsResponse = (TagsPublic);

export type TagsCreateTagData = {
    requestBody: TagCreate;
};

export type TagsCreateTagResponse = (TagPublic);

export type TagsSuggestTagsData = {
    limit?: number;
    q?: string;
};

export type TagsSuggestTagsResponse = (TagsSuggest);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (ResponseMessage);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (ResponseMessage);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (ResponseMessage);

export type UsersGetUserProfileData = {
    userId: string;
};

export type UsersGetUserProfileResponse = (UserProfileOut);

export type UsersFollowUserData = {
    userId: string;
};

export type UsersFollowUserResponse = (FollowStatus);

export type UsersUnfollowUserData = {
    userId: string;
};

export type UsersUnfollowUserResponse = (FollowStatus);

export type UsersListUserPostsData = {
    limit?: number;
    skip?: number;
    userId: string;
};

export type UsersListUserPostsResponse = (Array<PostPublic>);

export type UsersListUserAnsweredPostsData = {
    limit?: number;
    skip?: number;
    userId: string;
};

export type UsersListUserAnsweredPostsResponse = (Array<PostPublic>);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (ResponseMessage);

export type UtilsHealthCheckResponse = (boolean);