// This file is auto-generated by @hey-api/openapi-ts

/**
 * 作者信息（按 MVP 字段契约返回）。
 *
 * 约束/说明：
 * - 前端 `PostCard` 直接使用 `author.avatar` 作为图片 URL，因此后端必须返回该字段。
 * - 当前 `User` 模型没有头像与 bio 字段：本 MVP 先返回空字符串/None，由前端用 dicebear 兜底。
 * - `id` 为作者 public_id，用于跳转 TA 的资料页；已删除用户为 null。
 */
export type AuthorPublic = {
    id?: (string | null);
    name: string;
    avatar?: string;
    bio?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type FollowStatus = {
    following: boolean;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PostCreate = {
    title: string;
    body: string;
    tag_ids?: Array<(string)>;
};

export type PostPublic = {
    id: string;
    title: string;
    content: string;
    timestamp: string;
    comments: number;
    author: AuthorPublic;
    tags?: Array<TagPublic>;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ReplyCreate = {
    body: string;
};

export type ReplyPublic = {
    id: string;
    content: string;
    timestamp: string;
    author: AuthorPublic;
    post_id?: (string | null);
};

export type ResponseMessage = {
    message: string;
};

export type TagCreate = {
    name: string;
    description?: (string | null);
};

export type TagPublic = {
    id: string;
    name: string;
    slug: string;
    category?: (string | null);
    description?: (string | null);
    is_official?: boolean;
    owner_public_id?: (string | null);
};

export type TagsPublic = {
    data: Array<TagPublic>;
    count: number;
};

export type TagsSuggest = {
    data: Array<TagPublic>;
    count: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    username?: (string | null);
    phone_number?: (string | null);
    display_name?: (string | null);
    avatar_url?: (string | null);
    bio?: (string | null);
    profile_metadata?: {
        [key: string]: unknown;
    };
    password: string;
};

export type UserProfileOut = {
    user: UserPublicPreview;
    followers_count: number;
    following_count: number;
    is_following: (boolean | null);
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    username?: (string | null);
    phone_number?: (string | null);
    display_name?: (string | null);
    avatar_url?: (string | null);
    bio?: (string | null);
    profile_metadata?: {
        [key: string]: unknown;
    };
    id: string;
    date_joined?: (string | null);
};

/**
 * 对外展示的用户资料（不含邮箱等敏感字段）。
 */
export type UserPublicPreview = {
    id: string;
    full_name: (string | null);
    display_name: (string | null);
    username: (string | null);
    avatar_url: (string | null);
    bio: (string | null);
    date_joined: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
    username?: (string | null);
    phone_number?: (string | null);
    display_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    username?: (string | null);
    phone_number?: (string | null);
    display_name?: (string | null);
    avatar_url?: (string | null);
    bio?: (string | null);
    profile_metadata?: {
        [key: string]: unknown;
    };
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    username?: (string | null);
    phone_number?: (string | null);
    display_name?: (string | null);
    avatar_url?: (string | null);
    bio?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (ResponseMessage);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (ResponseMessage);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PostsCreatePostData = {
    requestBody: PostCreate;
};

export type PostsCreatePostResponse = (PostPublic);

export type PostsListPostsData = {
    limit?: number;
    skip?: number;
};

export type PostsListPostsResponse = (Array<PostPublic>);

export type PostsGetPostDetailData = {
    postId: string;
};

export type PostsGetPostDetailResponse = (PostPublic);

export type PostsListRepliesData = {
    postId: string;
};

export type PostsListRepliesResponse = (Array<ReplyPublic>);

export type PostsCreateReplyData = {
    postId: string;
    requestBody: ReplyCreate;
};

export type PostsCreateReplyResponse = (ReplyPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type TagsListTagsResponse = (TagsPublic);

export type TagsCreateTagData = {
    requestBody: TagCreate;
};

export type TagsCreateTagResponse = (TagPublic);

export type TagsSuggestTagsData = {
    limit?: number;
    q?: string;
};

export type TagsSuggestTagsResponse = (TagsSuggest);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (ResponseMessage);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (ResponseMessage);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (ResponseMessage);

export type UsersGetUserProfileData = {
    userId: string;
};

export type UsersGetUserProfileResponse = (UserProfileOut);

export type UsersFollowUserData = {
    userId: string;
};

export type UsersFollowUserResponse = (FollowStatus);

export type UsersUnfollowUserData = {
    userId: string;
};

export type UsersUnfollowUserResponse = (FollowStatus);

export type UsersListUserPostsData = {
    limit?: number;
    skip?: number;
    userId: string;
};

export type UsersListUserPostsResponse = (Array<PostPublic>);

export type UsersListUserAnsweredPostsData = {
    limit?: number;
    skip?: number;
    userId: string;
};

export type UsersListUserAnsweredPostsResponse = (Array<PostPublic>);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (ResponseMessage);

export type UtilsHealthCheckResponse = (boolean);