CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(150) UNIQUE,
  "phone_number" varchar(255) UNIQUE NOT NULL,
  "password" varchar(128),
  "display_name" varchar(150),
  "avatar_url" text,
  "is_active" boolean DEFAULT true,
  "profile_metadata" json,
  "date_joined" timestamp
);

CREATE TABLE "invites" (
  "id" integer PRIMARY KEY,
  "code" varchar(64) UNIQUE,
  "created_by_id" integer,
  "used_by_id" integer,
  "status" varchar(20),
  "expires_at" timestamp,
  "max_uses" integer DEFAULT 1,
  "used_count" integer DEFAULT 0
);

CREATE TABLE "tags" (
  "id" integer PRIMARY KEY,
  "name" varchar(50) UNIQUE,
  "slug" varchar(50) UNIQUE,
  "category" varchar(30)
);

CREATE TABLE "posts" (
  "id" integer PRIMARY KEY,
  "author_id" integer,
  "title" varchar(200),
  "body" text,
  "project_geom" geometry,
  "is_deleted" boolean DEFAULT false,
  "created_at" timestamp
);

CREATE TABLE "post_tags" (
  "post_id" integer,
  "tag_id" integer
);

CREATE TABLE "ai_sessions" (
  "id" integer PRIMARY KEY,
  "user_id" integer,
  "title" varchar(200),
  "environment_preset" json,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "ai_messages" (
  "id" integer PRIMARY KEY,
  "session_id" integer,
  "sequence_number" integer,
  "role" varchar(20),
  "content" text,
  "instant_override" json,
  "created_at" timestamp
);

CREATE TABLE "ai_answers" (
  "id" integer PRIMARY KEY,
  "message_id" integer UNIQUE,
  "raw_answer" text,
  "validated_answer" text,
  "risk_flags" json,
  "ragflow_trace_id" varchar(64)
);

CREATE TABLE "ai_citations" (
  "id" integer PRIMARY KEY,
  "answer_id" integer,
  "doc_id" varchar(128),
  "source_kind" varchar(20),
  "url" text,
  "bucket" varchar(255),
  "object_key" varchar(1024),
  "standard_code" varchar(100),
  "region" varchar(32)
);

CREATE UNIQUE INDEX ON "ai_messages" ("session_id", "sequence_number");

CREATE INDEX ON "ai_citations" ("object_key");

CREATE INDEX ON "ai_citations" ("standard_code");

COMMENT ON COLUMN "users"."username" IS '可选，与email一致';

COMMENT ON COLUMN "users"."profile_metadata" IS '用户预设: industry, region等';

COMMENT ON COLUMN "invites"."used_by_id" IS 'SET_NULL';

COMMENT ON COLUMN "invites"."status" IS 'pending/used/expired';

COMMENT ON TABLE "posts" IS 'GIS从业者交流区';

COMMENT ON COLUMN "posts"."project_geom" IS 'PostGIS SRID:4326';

COMMENT ON TABLE "post_tags" IS 'ManyToManyField 关联表';

COMMENT ON COLUMN "ai_sessions"."environment_preset" IS '初始 ArcGIS 版本/CRS 等';

COMMENT ON COLUMN "ai_messages"."sequence_number" IS '逻辑排序号，防止时间戳漂移';

COMMENT ON COLUMN "ai_messages"."role" IS 'user/assistant/system';

COMMENT ON COLUMN "ai_messages"."instant_override" IS '即时环境修正，覆盖 Session 预设';

COMMENT ON COLUMN "ai_citations"."source_kind" IS 'url / object_storage';

ALTER TABLE "invites" ADD FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "invites" ADD FOREIGN KEY ("used_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "posts" ADD FOREIGN KEY ("author_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "post_tags" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "post_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ai_sessions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ai_messages" ADD FOREIGN KEY ("session_id") REFERENCES "ai_sessions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ai_answers" ADD FOREIGN KEY ("message_id") REFERENCES "ai_messages" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ai_citations" ADD FOREIGN KEY ("answer_id") REFERENCES "ai_answers" ("id") DEFERRABLE INITIALLY IMMEDIATE;
