/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSearchRouteImport } from './routes/_layout/search'
import { Route as LayoutTopicsIndexRouteImport } from './routes/_layout/topics/index'
import { Route as LayoutSpacesIndexRouteImport } from './routes/_layout/spaces/index'
import { Route as LayoutKnowledgeIndexRouteImport } from './routes/_layout/knowledge/index'
import { Route as LayoutUUserIdRouteImport } from './routes/_layout/u/$userId'
import { Route as LayoutSpacesSpaceIdRouteImport } from './routes/_layout/spaces/$spaceId'
import { Route as LayoutPostNewRouteImport } from './routes/_layout/post/new'
import { Route as LayoutPostPostIdRouteImport } from './routes/_layout/post/$postId'
import { Route as LayoutKnowledgeSpaceIdRouteImport } from './routes/_layout/knowledge/$spaceId'
import { Route as LayoutKnowledgeSpaceIdIndexRouteImport } from './routes/_layout/knowledge/$spaceId/index'
import { Route as LayoutKnowledgeSpaceIdDocSlugRouteImport } from './routes/_layout/knowledge/$spaceId/$docSlug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSearchRoute = LayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTopicsIndexRoute = LayoutTopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSpacesIndexRoute = LayoutSpacesIndexRouteImport.update({
  id: '/spaces/',
  path: '/spaces/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKnowledgeIndexRoute = LayoutKnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUUserIdRoute = LayoutUUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSpacesSpaceIdRoute = LayoutSpacesSpaceIdRouteImport.update({
  id: '/spaces/$spaceId',
  path: '/spaces/$spaceId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPostNewRoute = LayoutPostNewRouteImport.update({
  id: '/post/new',
  path: '/post/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPostPostIdRoute = LayoutPostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKnowledgeSpaceIdRoute = LayoutKnowledgeSpaceIdRouteImport.update({
  id: '/knowledge/$spaceId',
  path: '/knowledge/$spaceId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKnowledgeSpaceIdIndexRoute =
  LayoutKnowledgeSpaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutKnowledgeSpaceIdRoute,
  } as any)
const LayoutKnowledgeSpaceIdDocSlugRoute =
  LayoutKnowledgeSpaceIdDocSlugRouteImport.update({
    id: '/$docSlug',
    path: '/$docSlug',
    getParentRoute: () => LayoutKnowledgeSpaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/knowledge/$spaceId': typeof LayoutKnowledgeSpaceIdRouteWithChildren
  '/post/$postId': typeof LayoutPostPostIdRoute
  '/post/new': typeof LayoutPostNewRoute
  '/spaces/$spaceId': typeof LayoutSpacesSpaceIdRoute
  '/u/$userId': typeof LayoutUUserIdRoute
  '/knowledge/': typeof LayoutKnowledgeIndexRoute
  '/spaces/': typeof LayoutSpacesIndexRoute
  '/topics/': typeof LayoutTopicsIndexRoute
  '/knowledge/$spaceId/$docSlug': typeof LayoutKnowledgeSpaceIdDocSlugRoute
  '/knowledge/$spaceId/': typeof LayoutKnowledgeSpaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/post/$postId': typeof LayoutPostPostIdRoute
  '/post/new': typeof LayoutPostNewRoute
  '/spaces/$spaceId': typeof LayoutSpacesSpaceIdRoute
  '/u/$userId': typeof LayoutUUserIdRoute
  '/knowledge': typeof LayoutKnowledgeIndexRoute
  '/spaces': typeof LayoutSpacesIndexRoute
  '/topics': typeof LayoutTopicsIndexRoute
  '/knowledge/$spaceId/$docSlug': typeof LayoutKnowledgeSpaceIdDocSlugRoute
  '/knowledge/$spaceId': typeof LayoutKnowledgeSpaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/search': typeof LayoutSearchRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/knowledge/$spaceId': typeof LayoutKnowledgeSpaceIdRouteWithChildren
  '/_layout/post/$postId': typeof LayoutPostPostIdRoute
  '/_layout/post/new': typeof LayoutPostNewRoute
  '/_layout/spaces/$spaceId': typeof LayoutSpacesSpaceIdRoute
  '/_layout/u/$userId': typeof LayoutUUserIdRoute
  '/_layout/knowledge/': typeof LayoutKnowledgeIndexRoute
  '/_layout/spaces/': typeof LayoutSpacesIndexRoute
  '/_layout/topics/': typeof LayoutTopicsIndexRoute
  '/_layout/knowledge/$spaceId/$docSlug': typeof LayoutKnowledgeSpaceIdDocSlugRoute
  '/_layout/knowledge/$spaceId/': typeof LayoutKnowledgeSpaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/search'
    | '/settings'
    | '/knowledge/$spaceId'
    | '/post/$postId'
    | '/post/new'
    | '/spaces/$spaceId'
    | '/u/$userId'
    | '/knowledge/'
    | '/spaces/'
    | '/topics/'
    | '/knowledge/$spaceId/$docSlug'
    | '/knowledge/$spaceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/search'
    | '/settings'
    | '/'
    | '/post/$postId'
    | '/post/new'
    | '/spaces/$spaceId'
    | '/u/$userId'
    | '/knowledge'
    | '/spaces'
    | '/topics'
    | '/knowledge/$spaceId/$docSlug'
    | '/knowledge/$spaceId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/search'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/knowledge/$spaceId'
    | '/_layout/post/$postId'
    | '/_layout/post/new'
    | '/_layout/spaces/$spaceId'
    | '/_layout/u/$userId'
    | '/_layout/knowledge/'
    | '/_layout/spaces/'
    | '/_layout/topics/'
    | '/_layout/knowledge/$spaceId/$docSlug'
    | '/_layout/knowledge/$spaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/topics/': {
      id: '/_layout/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof LayoutTopicsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/spaces/': {
      id: '/_layout/spaces/'
      path: '/spaces'
      fullPath: '/spaces/'
      preLoaderRoute: typeof LayoutSpacesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/knowledge/': {
      id: '/_layout/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof LayoutKnowledgeIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/u/$userId': {
      id: '/_layout/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof LayoutUUserIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/spaces/$spaceId': {
      id: '/_layout/spaces/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/spaces/$spaceId'
      preLoaderRoute: typeof LayoutSpacesSpaceIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/post/new': {
      id: '/_layout/post/new'
      path: '/post/new'
      fullPath: '/post/new'
      preLoaderRoute: typeof LayoutPostNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/post/$postId': {
      id: '/_layout/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof LayoutPostPostIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/knowledge/$spaceId': {
      id: '/_layout/knowledge/$spaceId'
      path: '/knowledge/$spaceId'
      fullPath: '/knowledge/$spaceId'
      preLoaderRoute: typeof LayoutKnowledgeSpaceIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/knowledge/$spaceId/': {
      id: '/_layout/knowledge/$spaceId/'
      path: '/'
      fullPath: '/knowledge/$spaceId/'
      preLoaderRoute: typeof LayoutKnowledgeSpaceIdIndexRouteImport
      parentRoute: typeof LayoutKnowledgeSpaceIdRoute
    }
    '/_layout/knowledge/$spaceId/$docSlug': {
      id: '/_layout/knowledge/$spaceId/$docSlug'
      path: '/$docSlug'
      fullPath: '/knowledge/$spaceId/$docSlug'
      preLoaderRoute: typeof LayoutKnowledgeSpaceIdDocSlugRouteImport
      parentRoute: typeof LayoutKnowledgeSpaceIdRoute
    }
  }
}

interface LayoutKnowledgeSpaceIdRouteChildren {
  LayoutKnowledgeSpaceIdDocSlugRoute: typeof LayoutKnowledgeSpaceIdDocSlugRoute
  LayoutKnowledgeSpaceIdIndexRoute: typeof LayoutKnowledgeSpaceIdIndexRoute
}

const LayoutKnowledgeSpaceIdRouteChildren: LayoutKnowledgeSpaceIdRouteChildren =
  {
    LayoutKnowledgeSpaceIdDocSlugRoute: LayoutKnowledgeSpaceIdDocSlugRoute,
    LayoutKnowledgeSpaceIdIndexRoute: LayoutKnowledgeSpaceIdIndexRoute,
  }

const LayoutKnowledgeSpaceIdRouteWithChildren =
  LayoutKnowledgeSpaceIdRoute._addFileChildren(
    LayoutKnowledgeSpaceIdRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutSearchRoute: typeof LayoutSearchRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutKnowledgeSpaceIdRoute: typeof LayoutKnowledgeSpaceIdRouteWithChildren
  LayoutPostPostIdRoute: typeof LayoutPostPostIdRoute
  LayoutPostNewRoute: typeof LayoutPostNewRoute
  LayoutSpacesSpaceIdRoute: typeof LayoutSpacesSpaceIdRoute
  LayoutUUserIdRoute: typeof LayoutUUserIdRoute
  LayoutKnowledgeIndexRoute: typeof LayoutKnowledgeIndexRoute
  LayoutSpacesIndexRoute: typeof LayoutSpacesIndexRoute
  LayoutTopicsIndexRoute: typeof LayoutTopicsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSearchRoute: LayoutSearchRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutKnowledgeSpaceIdRoute: LayoutKnowledgeSpaceIdRouteWithChildren,
  LayoutPostPostIdRoute: LayoutPostPostIdRoute,
  LayoutPostNewRoute: LayoutPostNewRoute,
  LayoutSpacesSpaceIdRoute: LayoutSpacesSpaceIdRoute,
  LayoutUUserIdRoute: LayoutUUserIdRoute,
  LayoutKnowledgeIndexRoute: LayoutKnowledgeIndexRoute,
  LayoutSpacesIndexRoute: LayoutSpacesIndexRoute,
  LayoutTopicsIndexRoute: LayoutTopicsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
